services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - app_network
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "8081:8081"
    environment:
      - DATABASE_URL=postgres://myuser:mypassword@db:5432/dbname?sslmode=disable
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: postgres:13
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: dbname
    ports:
      - "5432:5432"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge