version: '3.8'

services:
  postgres:
    build: ./database
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: monitoring

  backend:
    build: ./backend
    container_name: backend_service
    restart: always
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_USER: admin
      DB_PASSWORD: secret
      DB_NAME: monitoring
    ports:
      - "8080:8080"

