# GET запрос для получения всех контейнеров
# curl http://localhost:8081/ping
#curl http://localhost:8081/containers
GET http://192.168.1.2:8081/containers

##
### Разделитель для другого запроса

# POST запрос для отправки данных о пинге контейнера
POST http://localhost:8081/ping
Content-Type: application/json

{
  "ip_address": "192.168.1.2",
  "success": true
}